Description: Sets up the underlying infrastructure for hosting a simple SPA
Parameters:
  BucketName:
    Description: name for the S3 bucket hosting the SPA
    Type: String
Resources:
  SPAS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: { 'Ref': 'BucketName' }

  DocBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: 'SPAS3Bucket'
      PolicyDocument:
        {
          'Version': '2012-10-17',
          'Statement':
            [
              {
                'Sid': 'PublicReadGetObject',
                'Effect': 'Allow',
                'Principal': '*',
                'Action': 's3:GetObject',
                'Resource':
                  !Join ['', ['arn:aws:s3:::', { 'Ref': 'BucketName' }, '/*']],
              },
            ],
        }